services:
  app:
    build: .
    container_name: laravel-polls
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - ./public:/var/www/html/public
      - ./.env:/var/www/html/.env  # Mount .env into container
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      DB_FOREIGN_KEYS: "true"
